[package]
name = "libsignalk"
version = "0.1.0"
authors = ["Tim Mathews <tim@signalk.org>"]
license = "Apache-2.0"
build = "build.rs"

[build-dependencies]
syntex = "*"
serde_codegen = "*"

[dependencies]
serde = "*"
serde_xml = "*"
